/*
*	Base de dados
*	NLLWS (a.k.a NICHOLAS LOPES LEITE WEB SERIVICE)
* 
*	Script para criação da tabela CURSO
* 
*	@author Nicholas Leite <nicklleite@gmail.com>
*	@repo https://github.com/nicklleite/nllws
*	@date 29/08/2017
*
*/

-- SEQUENCE para a chave primária
CREATE SEQUENCE CURSO_SEQ
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
NO CYCLE;

-- Tabela CURSO
CREATE TABLE CURSO (
    ID BIGINT NOT NULL,
    EMPRESA_ID BIGINT NOT NULL,

    COD VARCHAR(5) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    DM_TIPO VARCHAR(2) NOT NULL,
    DM_SITUACAO VARCHAR(2) NOT NULL,

    CONSTRAINT CURSO_PK PRIMARY KEY (ID)
);

ALTER TABLE CURSO
    ADD CONSTRAINT CURSO_EMPRESA_FK FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA (ID);
CREATE INDEX CURSO_EMPRESA_FK_I
    ON CURSO (EMPRESA_ID);

ALTER TABLE CURSO
    ADD CONSTRAINT CURSO_DMSITUACAO_CK CHECK CURSO_DMSITUACAO_CK IN ('0', '1');
INSERT INTO DOMINIO
VALUES
    (NEXTVAL('DOMINIO_SEQ'), '0', 'CURSO.DM_SITUACAO', 'Ativo'),
    (NEXTVAL('DOMINIO_SEQ'), '1', 'CURSO.DM_SITUACAO', 'Não Ativo');

ALTER TABLE CURSO
    ADD CONSTRAINT CURSO_UK UNIQUE (EMPRESA_ID, COD);