/**
 *	Base de dados
 *	NLLWS (a.k.a NICHOLAS LOPES LEITE WEB SERIVICE)
 * 
 *	Script para criação das tabelas referentes ao módulo DEPARTAMENTO
 * 
 *	@author Nicholas Leite <nicklleite@gmail.com>
 *	@repo https://github.com/nicklleite/nllws
 *	@date 25/08/2017
 *
 */

-- SEQUENCE para a chave primária
CREATE SEQUENCE DEPARTAMENTO_SEQ
START WITH 1
INCREMENT BY 1
NO MAXVALUE;

-- Tabela DEPARTAMENTO
DROP TABLE IF EXISTS DEPARTAMENTO;
CREATE TABLE DEPARTAMENTO (
    ID BIGINT NOT NULL CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY DEFAULT NEXTVAL('DEPARTAMENTO_SEQ'),
    EMPRESA_ID BIGINT NOT NULL,
    COD VARCHAR(4) NOT NULL,
    DESCR VARCHAR(150) NOT NULL,
    _INCLUIDO_POR_ID BIGINT NOT NULL,
	_DATA_INCLUSAO TIMESTAMP NOT NULL,
	_ALTERADO_POR_ID BIGINT NOT NULL,
	_DATA_ALTERACAO TIMESTAMP NOT NULL,

    CONSTRAINT DEPARTAMENTO_EMPRESA_FK FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
    CONSTRAINT DOMINIO_INCLUIDOPOR_FK FOREIGN KEY (_INCLUIDO_POR_ID) REFERENCES USUARIO(ID),
	CONSTRAINT DOMINIO_ALTERADOPOR_FK FOREIGN KEY (_ALTERADO_POR_ID) REFERENCES USUARIO(ID)
);

ALTER SEQUENCE DEPARTAMENTO_SEQ OWNED BY DOMINIO.ID;