/*
*	Base de dados
*	NLLWS (a.k.a NICHOLAS LOPES LEITE WEB SERIVICE)
* 
*	Script para criação da tabela DOCUMENTOS
* 
*	@author Nicholas Leite <nicklleite@gmail.com>
*	@repo https://github.com/nicklleite/nllws
*	@date 01/09/2017
*
*/

-- SEQUENCE para a chave primária
CREATE SEQUENCE DOCUMENTOS_SEQ
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
NO CYCLE;

-- Tabela DOCUMENTOS
DROP TABLE IF EXISTS DOCUMENTOS;
CREATE TABLE DOCUMENTOS (
    ID BIGINT NOT NULL DEFAULT NEXTVAL('DOCUMENTOS_SEQ'),
    EMPRESA_ID BIGINT NOT NULL,
    DISCIPLINA_ID BIGINT NOT NULL,

    COD VARCHAR(10) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(30) NOT NULL,
    TAMANHO VARCHAR(10) NOT NULL,
    CAMINHO VARCHAR(100) NOT NULL,
    OBSERVACOES TEXT NOT NULL,
    MENSAGENS_ATIVIDADE TEXT NOT NULL,
    DATA_ENVIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    DM_SITUACAO VARCHAR(1) NOT NULL,

    CONSTRAINT DOCUMENTOS_PK PRIMARY KEY (ID)
);

ALTER SEQUENCE DOCUMENTOS_SEQ OWNED BY DOCUMENTOS.ID;

ALTER TABLE DOCUMENTOS
    ADD CONSTRAINT DOCUMENTOS_EMPRESA_FK FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA (ID);
CREATE INDEX DOCUMENTOS_EMPRESA_FK_I
    ON DOCUMENTOS (EMPRESA_ID);

ALTER TABLE DOCUMENTOS
    ADD CONSTRAINT DOCUMENTOS_DISCIPLINA_FK FOREIGN KEY (DISCIPLINA_ID) REFERENCES DISCIPLINA (ID);
CREATE INDEX DOCUMENTOS_DISCIPLINA_FK_I
    ON DOCUMENTOS (DISCIPLINA_ID);

ALTER TABLE DOCUMENTOS
    ADD CONSTRAINT DOCUMENTOS_DMSITUACAO_CK CHECK (DM_SITUACAO IN ('0', '1', '2'));
INSERT INTO DOMINIO
VALUES
    (NEXTVAL('DOMINIO_SEQ'), '1', 'DOCUMENTOS.DM_SITUACAO', 'Disponível'),
    (NEXTVAL('DOMINIO_SEQ'), '2', 'DOCUMENTOS.DM_SITUACAO', 'Disponível - Professor'),
    (NEXTVAL('DOMINIO_SEQ'), '3', 'DOCUMENTOS.DM_SITUACAO', 'Indisponível');

ALTER TABLE DOCUMENTOS
    ADD CONSTRAINT DOCUMENTOS_UK UNIQUE (COD);