/**
 * Base de dados - EducaTech
 *
 * Script para criação da tabela DOMINIO
 *
 * @author Nicholas Leite <nicklleite@gmail.com>
 * @see https://github.com/nicklleite/educatech
 * @date 24/08/2017
 * 
 */

-- SEQUENCE para a chave primária
CREATE SEQUENCE DOMINIO_SEQ
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
NO CYCLE;

-- Tabela DOMINIO
DROP TABLE IF EXISTS DOMINIO;
CREATE TABLE DOMINIO (
	ID BIGINT NOT NULL DEFAULT NEXTVAL('DOMINIO_SEQ'),
	VL VARCHAR(5) NOT NULL,
	DOMINIO VARCHAR(60) NOT NULL,
	DESCR VARCHAR(150) NOT NULL,

	CONSTRAINT DOMINIO_PK PRIMARY KEY (ID)
);

ALTER SEQUENCE DOMINIO_SEQ OWNED BY DOMINIO.ID;