/*
*	Base de dados
*	NLLWS (a.k.a NICHOLAS LOPES LEITE WEB SERIVICE)
* 
*	Script para criação da tabela DOMINIO
* 
*	@author Nicholas Leite <nicklleite@gmail.com>
*	@repo https://github.com/nicklleite/nllws
*	@date 24/08/2017
*
*/

-- SEQUENCE para a chave primária
CREATE SEQUENCE DOMINIO_SEQ
START WITH 1
INCREMENT BY 1
NO MAXVALUE;

-- Tabela DOMINIO
CREATE TABLE DOMINIO (
	ID BIGINT NOT NULL CONSTRAINT DOMINIO_PK PRIMARY KEY DEFAULT NEXTVAL('DOMINIO_SEQ'),
	EMPRESA_ID BIGINT NOT NULL,
	VL SMALLINT NOT NULL CONSTRAINT DOMINIO_VL_CK CHECK (VL < 999),
	DESCR VARCHAR(150) NOT NULL,
	_INCLUIDO_POR_ID BIGINT NOT NULL,
	_DATA_INCLUSAO TIMESTAMP NOT NULL,
	_ALTERADO_POR_ID BIGINT NOT NULL,
	_DATA_ALTERACAO TIMESTAMP NOT NULL,

	CONSTRAINT DOMINIO_EMPRESAID_FK FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID),
	CONSTRAINT DOMINIO_INCLUIDOPOR_FK FOREIGN KEY (_INCLUIDO_POR_ID) REFERENCES USUARIO(ID),
	CONSTRAINT DOMINIO_ALTERADOPOR_FK FOREIGN KEY (_ALTERADO_POR_ID) REFERENCES USUARIO(ID)
);

ALTER SEQUENCE DOMINIO_SEQ OWNED BY DOMINIO.ID;