/*
*	Base de dados
*	NLLWS (a.k.a NICHOLAS LOPES LEITE WEB SERIVICE)
* 
*	Script para criação das tabelas referentes ao módulo EMPRESA
* 
*	@author Nicholas Leite <nicklleite@gmail.com>
*	@repo https://github.com/nicklleite/nllws
*	@date 24/08/2017
*
*/

-- SEQUENCE para a chave primária
CREATE SEQUENCE EMPRESA_SEQ
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
NO CYCLE;

-- Tabela EMPRESA
DROP TABLE IF EXISTS EMPRESA;
CREATE TABLE EMPRESA (
	ID BIGINT NOT NULL DEFAULT NEXTVAL('EMPRESA_SEQ'),
    INSTITUICAO_ID BIGINT NOT NULL,
    RAZAO_SOCIAL VARCHAR(200) NOT NULL,
    NOME_FANTASIA VARCHAR(200) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    DM_SITUACAO VARCHAR(1) NOT NULL DEFAULT 0,
    
    CEP VARCHAR(8) NOT NULL,
    CIDADE_ID BIGINT NOT NULL,
    DM_LOGRADOURO VARCHAR(3) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(5) NOT NULL,
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR (200) NOT NULL,

    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    
    CONSTRAINT EMPRESA_PK PRIMARY KEY (ID)
);

ALTER SEQUENCE EMPRESA_SEQ OWNED BY EMPRESA.ID;

-- CONSTRAINTS
ALTER TABLE EMPRESA
    ADD CONSTRAINT EMPRESA_DMSITUACAO_CK CHECK (DM_SITUACAO IN ('0', '1'));

INSERT INTO DOMINIO
VALUES
    (NEXTVAL('DOMINIO_SEQ'), '1', 'EMPRESA.DM_SITUACAO', 'Inativa'),
    (NEXTVAL('DOMINIO_SEQ'), '2', 'EMPRESA.DM_SITUACAO', 'Ativa');

ALTER TABLE EMPRESA
    ADD CONSTRAINT EMPRESA_DMLOGRADOURO_CK CHECK (DM_LOGRADOURO IN ('R', 'AV', 'TV', 'VL', 'ROD'));

INSERT INTO DOMINIO
VALUES
    (NEXTVAL('DOMINIO_SEQ'), 'R', 'EMPRESA.DM_LOGRADOURO', 'Rua'),
    (NEXTVAL('DOMINIO_SEQ'), 'AV', 'EMPRESA.DM_LOGRADOURO', 'Avenida'),
    (NEXTVAL('DOMINIO_SEQ'), 'TV', 'EMPRESA.DM_LOGRADOURO', 'Travessa'),
    (NEXTVAL('DOMINIO_SEQ'), 'VL', 'EMPRESA.DM_LOGRADOURO', 'Vila'),
    (NEXTVAL('DOMINIO_SEQ'), 'ROD', 'EMPRESA.DM_LOGRADOURO', 'Rodovia');

ALTER TABLE EMPRESA
    ADD CONSTRAINT EMPRESA_CIDADE_FK FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (ID);
CREATE INDEX EMPRESA_CIDADE_FK_I
    ON EMPRESA (CIDADE_ID);

ALTER TABLE EMPRESA
    ADD CONSTRAINT EMPRESA_INSTITUICAO_FK FOREIGN KEY (INSTITUICAO_ID) REFERENCES INSTITUICAO (ID);
CREATE INDEX EMPRESA_INSTITUICAO_FK_I
    ON EMPRESA (INSTITUICAO_ID);

ALTER TABLE EMPRESA
    ADD CONSTRAINT EMPRESA_UK_1 UNIQUE(CNPJ);

ALTER TABLE EMPRESA
    ADD CONSTRAINT EMPRESA_UK_2 UNIQUE(EMAIL);