/*
* Base de dados
* NLLWS (a.k.a NICHOLAS LOPES LEITE WEB SERIVICE)
* 
* Script para criação das tabelas referentes ao módulo EMPRESA
* 
* @author Nicholas Leite <nicklleite@gmail.com>
* @repo https://github.com/nicklleite/nllws
* @date 24/08/2017
*/

-- SEQUENCE para a chave primária
CREATE SEQUENCE EMPRESA_SEQ
START WITH 1
INCREMENT BY 1
NO MAXVALUE;

-- Tabela EMPRESA
DROP TABLE IF EXISTS EMPRESA;
CREATE TABLE EMPRESA (
	ID BIGINT NOT NULL CONSTRAINT EMPRESA_PK PRIMARY KEY DEFAULT NEXTVAL('EMPRESA_SEQ'),
    CIDADE_ID BIGINT NOT NULL, -- FOREIGN KEY
    RAZAO_SOCIAL VARCHAR(200) NOT NULL,
    NOME_FANTASIA VARCHAR(200) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    BAIRRO VARCHAR (200) NOT NULL,
    DM_SITUACAO SMALLINT NOT NULL DEFAULT 0 CONSTRAINT EMPRESA_DMSITUACAO_CK CHECK (DM_ROLE < 99),
);



