/*
*	Base de dados
*	NLLWS (a.k.a NICHOLAS LOPES LEITE WEB SERIVICE)
* 
*	Script para criação das tabelas referentes ao módulo EMPRESA
* 
*	@author Nicholas Leite <nicklleite@gmail.com>
*	@repo https://github.com/nicklleite/nllws
*	@date 24/08/2017
*
*/

-- SEQUENCE para a chave primária
CREATE SEQUENCE EMPRESA_SEQ
START WITH 1
INCREMENT BY 1
NO MAXVALUE;

-- Tabela EMPRESA
DROP TABLE IF EXISTS EMPRESA;
CREATE TABLE EMPRESA (
	ID BIGINT NOT NULL CONSTRAINT EMPRESA_PK PRIMARY KEY DEFAULT NEXTVAL('EMPRESA_SEQ'),
    RAZAO_SOCIAL VARCHAR(200) NOT NULL,
    NOME_FANTASIA VARCHAR(200) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    DM_SITUACAO SMALLINT NOT NULL DEFAULT 0 CONSTRAINT EMPRESA_DMSITUACAO_CK CHECK (DM_SITUACAO IN (0, 1)),
    
    CEP VARCHAR(8) NOT NULL,
    CIDADE_ID BIGINT NOT NULL,
    DM_LOGRADOURO VARCHAR(2) NOT NULL CONSTRAINT EMPRESA_DMLOGRADOURO_CK CHECK (DM_LOGRADOURO IN ('R', 'AV', 'TV', 'VL', 'ROD')),
    ENDERECO VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(5) NOT NULL,
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR (200) NOT NULL,

    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(255) NOT NULL,
    
    CONSTRAINT EMPRESA_UK UNIQUE(ID, CNPJ, EMAIL),
    CONSTRAINT EMPRESA_CIDADE_FK FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (ID)
);

ALTER SEQUENCE EMPRESA_SEQ OWNED BY EMPRESA.ID;

-- Incluir as tabelas ESTADO e CIDADE (projeto no GitHub).