/*
*	Base de dados
*	NLLWS (a.k.a NICHOLAS LOPES LEITE WEB SERIVICE)
* 
*	Script para criação da tabela INSTITUICAO
* 
*	@author Nicholas Leite <nicklleite@gmail.com>
*	@repo https://github.com/nicklleite/nllws
*	@date 28/08/2017
*
*/

-- SEQUENCE para a chave primária
CREATE SEQUENCE INSTITUICAO_SEQ
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
NO CYCLE;

-- Tabela DOMINIO
CREATE TABLE INSTITUICAO (
    ID BIGINT NOT NULL CONSTRAINT DOMINIO_PK PRIMARY KEY DEFAULT NEXTVAL('INSTITUICAO_SEQ'),
    COD VARCHAR(3) NOT NULL,
    DM_TIPO SMALLINT NOT NULL,
    NOME VARCHAR(150) NOT NULL
);

ALTER SEQUENCE DOMINIO_SEQ OWNED BY DOMINIO.ID;

-- COMENTÁRIOS

-- CONSTRAINTS
ALTER TABLE INSTITUICAO
    ADD CONSTRAINT DMTIPO_CK CHECK DM_TIPO IN (0, 1, 2);

INSERT INTO DOMINIO
VALUES
	(NEXTVAL('DOMINIO_SEQ'), 0, 'INSTITUICAO.DM_TIPO', 'Faculdade'),
	(NEXTVAL('DOMINIO_SEQ'), 1, 'INSTITUICAO.DM_TIPO', 'Centro Universitario'),
    (NEXTVAL('DOMINIO_SEQ'), 2, 'INSTITUICAO.DM_TIPO', 'Universidade')

ALTER TABLE INSTITUICAO
    ADD CONSTRAINT INSTITUICAO_UK UNIQUE (COD);

-- INSERTS
-- INSERT INTO INSTITUICAO