/*
*	Base de dados
*	NLLWS (a.k.a NICHOLAS LOPES LEITE WEB SERIVICE)
* 
*	Script para criação da tabela INSTITUICAO
* 
*	@author Nicholas Leite <nicklleite@gmail.com>
*	@repo https://github.com/nicklleite/nllws
*	@date 28/08/2017
*
*/

-- SEQUENCE para a chave primária
CREATE SEQUENCE INSTITUICAO_SEQ
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
NO CYCLE;

-- Tabela DOMINIO
DROP TABLE IF EXISTS INSTITUICAO;
CREATE TABLE INSTITUICAO (
    ID BIGINT NOT NULL DEFAULT NEXTVAL('INSTITUICAO_SEQ'),
    COD VARCHAR(3) NOT NULL,
    DM_TIPO VARCHAR(1) NOT NULL,
    NOME VARCHAR(150) NOT NULL,

    CONSTRAINT INSTITUICAO_PK PRIMARY KEY (ID)
);

ALTER SEQUENCE INSTITUICAO_SEQ OWNED BY INSTITUICAO.ID;

ALTER TABLE INSTITUICAO
    ADD CONSTRAINT DMTIPO_CK CHECK (DM_TIPO IN ('0', '1', '2'));

INSERT INTO DOMINIO
VALUES
	(NEXTVAL('DOMINIO_SEQ'), '0', 'INSTITUICAO.DM_TIPO', 'Faculdade'),
	(NEXTVAL('DOMINIO_SEQ'), '1', 'INSTITUICAO.DM_TIPO', 'Centro Universitario'),
    (NEXTVAL('DOMINIO_SEQ'), '2', 'INSTITUICAO.DM_TIPO', 'Universidade');

ALTER TABLE INSTITUICAO
    ADD CONSTRAINT INSTITUICAO_UK UNIQUE (COD);