/*
*	Base de dados
*	NLLWS (a.k.a NICHOLAS LOPES LEITE WEB SERIVICE)
* 
*	Script para criação da tabela NOTAS
* 
*	@author Nicholas Leite <nicklleite@gmail.com>
*	@repo https://github.com/nicklleite/nllws
*	@date 01/09/2017
*
*/

-- SEQUENCE para a chave primária
CREATE SEQUENCE NOTAS_SEQ
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
NO CYCLE;

-- Tabela NOTAS
CREATE TABLE NOTAS (
    ID BIGINT NOT NULL,
    ALUNO_ID BIGINT NOT NULL,
    DISCIPLINA_ID BIGINT NOT NULL,

    NOTA_P1 NUMERIC(3,2) NOT NULL,
    NOTA_P2 NUMERIC(3,2) NOT NULL,

    CONSTRAINT NOTAS_PK PRIMARY KEY (ID)
);

ALTER TABLE NOTAS
    ADD CONSTRAINT NOTAS_ALUNO_FK FOREIGN KEY (ALUNO_ID) REFERENCES ALUNO (ID);
CREATE INDEX NOTAS_ALUNO_FK_I
    ON NOTAS (ALUNO_ID);

ALTER TABLE NOTAS
    ADD CONSTRAINT NOTAS_DISCIPLINA_FK FOREIGN KEY (DISCIPLINA_ID) REFERENCES DISCIPLINA (ID);
CREATE INDEX NOTAS_DISCIPLINA_FK_I
    ON NOTAS (DISCIPLINA_ID);