/*
*	Base de dados
*	NLLWS (a.k.a NICHOLAS LOPES LEITE WEB SERIVICE)
* 
*	Script para criação da tabela PESSOA
* 
*	@author Nicholas Leite <nicklleite@gmail.com>
*	@repo https://github.com/nicklleite/nllws
*	@date 28/08/2017
*
*/

-- SEQUENCE para a chave primária
CREATE SEQUENCE PESSOA_SEQ
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
NO CYCLE;

-- Tabela PESSOA
CREATE TABLE PESSOA (
    ID BIGINT NOT NULL,
    EMPRESA_ID BIGINT NOT NULL,

    NOME VARCHAR(150) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    DATA_NASCIMENTO VARCHAR(10) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    CIDADE_ID BIGINT NOT NULL,
    DM_LOGRADOURO VARCHAR(2) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(5) NOT NULL,
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR (200) NOT NULL,

    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,

    DATA_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PESSOA_PK PRIMARY KEY (ID)

);

ALTER SEQUENCE PESSOA_SEQ OWNED BY PESSOA.ID;

ALTER TABLE PESSOA
    ADD CONSTRAINT PESSOA_EMPRESA_FK FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA (ID);
CREATE INDEX PESSOA_EMPRESA_FK_I
    ON PESSOA (EMPRESA_ID);

ALTER TABLE PESSOA
    ADD CONSTRAINT PESSOA_CIDADE_FK FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (ID);
CREATE INDEX PESSOA_CIDADE_FK_I
    ON PESSOA (CIDADE_ID);

ALTER TABLE PESSOA
    ADD CONSTRAINT PESSOA_DMLOGRADOURO_CK CHECK (DM_LOGRADOURO IN ('R', 'AV', 'TV', 'VL', 'ROD'));
INSERT INTO DOMINIO
VALUES
    (NEXTVAL('DOMINIO_SEQ'), 'R', 'PESSOA.DM_LOGRADOURO', 'Rua'),
    (NEXTVAL('DOMINIO_SEQ'), 'AV', 'PESSOA.DM_LOGRADOURO', 'Avenida'),
    (NEXTVAL('DOMINIO_SEQ'), 'TV', 'PESSOA.DM_LOGRADOURO', 'Travessa'),
    (NEXTVAL('DOMINIO_SEQ'), 'VL', 'PESSOA.DM_LOGRADOURO', 'Vila'),
    (NEXTVAL('DOMINIO_SEQ'), 'ROD', 'PESSOA.DM_LOGRADOURO', 'Rodovia');

ALTER TABLE PESSOA
    ADD CONSTRAINT PESSOA_UK_1 UNIQUE (CPF);

ALTER TABLE PESSOA
    ADD CONSTRAINT PESSOA_UK_2 UNIQUE (EMAIL);