/*
* Base de dados
* NLLWS (a.k.a NICHOLAS LOPES LEITE WEB SERIVICE)
* 
* Script para criação das tabelas referentes ao módulo USUARIO
* 
* @author Nicholas Leite <nicklleite@gmail.com>
* @repo https://github.com/nicklleite/nllws
* @date 24/08/2017
*/

-- SEQUENCE para a chave primária
CREATE SEQUENCE USUARIO_SEQ
START WITH 1
INCREMENT BY 1
NO MAXVALUE;

CREATE TABLE USUARIO (
	ID BIGINT NOT NULL CONSTRAINT USUARIO_PK PRIMARY KEY DEFAULT nextval('USUARIO_SEQ'),
	EMPRESA_ID BIGINT NOT NULL
	DM_TIPO SMALLINT NOT NULL DEFAULT 1 CONSTRAINT USUARIO_DMROLE_CK CHECK (DM_ROLE < 99),
	DM_SITUACAO SMALLINT NOT NULL DEFAULT 0 CONSTRAINT USUARIO_DMSITUACAO_CK CHECK (DM_ROLE < 99),
	DM_SETOR SMALLINT NOT NULL DEFAULT 0 CONSTRAINT USUARIO_DMSETOR_CK CHECK (DM_SETOR < 999)
);

ALTER SEQUENCE USERS_SEQ OWNED BY USERS.ID