/*
* Base de dados
* NLLWS (a.k.a NICHOLAS LOPES LEITE WEB SERIVICE)
* 
* Script para criação das tabelas referentes ao módulo USUARIO
* 
* @author Nicholas Leite <nicklleite@gmail.com>
* @repo https://github.com/nicklleite/nllws
* @date 24/08/2017
*/

-- SEQUENCE para a chave primária
CREATE SEQUENCE USUARIO_SEQ
START WITH 1
INCREMENT BY 1
NO MAXVALUE;

-- Tabela USUARIO
DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO (
	ID BIGINT NOT NULL CONSTRAINT USUARIO_PK PRIMARY KEY DEFAULT NEXTVAL('USUARIO_SEQ'),
	EMPRESA_ID BIGINT NOT NULL,
	LOGIN VARCHAR(100) NOT NULL,

	NOME_COMPLETO VARCHAR(150) NOT NULL,
	DEPARTAMENTO_ID BIGINT NOT NULL,
	CEP VARCHAR(8) NOT NULL,
    CIDADE_ID BIGINT NOT NULL,
    DM_LOGRADOURO VARCHAR(2) NOT NULL CONSTRAINT EMPRESA_DMLOGRADOURO_CK CHECK (DM_LOGRADOURO IN ('R', 'AV', 'TV', 'VL', 'ROD')),
    ENDERECO VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(5) NOT NULL,
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR (200) NOT NULL,

    EMAIL VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(255) NOT NULL,

	DM_SITUACAO SMALLINT NOT NULL DEFAULT 0 CONSTRAINT USUARIO_DMSITUACAO_CK CHECK (0, 1, 2, 3),

	CONSTRAINT USUARIO_DEPARTAMENTO_FK FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTO (ID),
	CONSTRAINT USUARIO_EMPRESA_FK FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA (ID),
	CONSTRAINT USUARIO_UK UNIQUE (ID, LOGIN, EMAIL)
);

-- DM_SITUACAO
---- 0: Inativo
---- 1: Ativo
---- 2: Sem senha
---- 3: Bloqueado

-- DM_TIPO_PESSOA
---- 'F': Física
---- 'J': Jurídica




ALTER SEQUENCE USERS_SEQ OWNED BY USERS.ID